config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :profiles, only: [:index, :show, :edit, :update] do
    member do
     delete :unfollow
     post :follow
    end
  end

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user, foreign_key: "follower_id"
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tweets

  has_many :followed, foreign_key: 'following_id', class_name: 'Follow'
  has_many :followers, through: 'followed', source: 'user'

  def following
    User.joins(:followed).where(follows: { follower_id: id })
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	order = params[:order_by].present? ? params[:order_by] : 'DESC'
  	@tweets = Tweet.includes(user: :followed).where(users: {follows: {follower_id: 1}}).order("tweets.created_at #{order}")
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.includes(:followed).where.not(id: current_user.id)
  end

  def show
  end

  def unfollow
    Follow.find_by(follower_id: current_user.id, following_id: params[:id]).destroy
    flash[:notice] = "Unfollowed successfully"
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to request.env["HTTP_REFERER"]
    else
      redirect_to profile_path(current_user)
    end
  end

  def follow
    follow = Follow.find_or_initialize_by(follower_id: current_user.id, following_id: params[:id])
    if follow.persisted?
      flash[:notice] = "Already following"
    else
      flash[:notice] = "Unfollowed successfully"
      follow.save
    end
    if request.env["HTTP_REFERER"].present? and request.env["HTTP_REFERER"] != request.env["REQUEST_URI"]
      redirect_to request.env["HTTP_REFERER"]
    else
      redirect_to profiles_path
    end
  end

  private

    def load_user
      @user = User.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/home/_tweets.html.erb
<% tweets.each do |tweet| %>
  <p>
    <b><%= link_to tweet.user.email, profile_path(tweet.user_id) %>:</b>
    <br>
    <%= tweet.created_at.strftime("%Y-%m-%d %H:%M %p") %>
    <br/>
    <%= tweet.text %>
  </p>
<% end %>

app/views/home/index.html.erb
<h1>Tweets from your followings:</h1>

<div style="width:40%;margin-left: 30%;"/>
  <h5>
    <% if params[:order_by]=="ASC" %>
      <%= link_to "Order by Newest First", root_path({order_by: "DESC"}), class: 'float_right' %></b>
    <% else %>
      <%= link_to "Order by Oldest First", root_path({order_by: "ASC"}), class: 'float_right' %></b>
    <% end %>
  </h5>
  <br>
  <%= render partial: '/home/tweets', locals: { tweets: @tweets } %>
<div>

app/views/layouts/_header.html.erb
<p class="header">
  <% if current_user.present? %>
    <%=link_to "Tweets", root_path, class: 'padding_10px' %>
    <%=link_to "All Users", profiles_path, class: 'padding_10px' %>
    <%=link_to "My Profile", profile_path(current_user.id), class: 'padding_10px' %>
    <%=link_to "Logout", destroy_user_session_path, method: :delete, class: 'padding_10px' %>
  <% else %>
    <%=link_to "Login", new_user_session_path %>
  <% end %>
</p>
<% if notice.present? %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert.present? %>
  <p class="alert"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterLikeApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "/layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/profiles/index.html.erb
<h1> Users on App</h1>
<% if @users.present? %>
  <table>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <% if user.followers.where(id: current_user.id).present? %>
          	<td><%= link_to "Unfollow", unfollow_profile_path(user.id), method: :delete %></td>
          <% else %>
            <td><%= link_to "Follow", follow_profile_path(user.id), method: :post %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  No user have joined the network yet. You will see other users once they join the network.
<% end %>

app/views/profiles/show.html.erb
<h1>Profile</h1>
<p>
  <b>User:</b>
  <%= @user.email%>
  <% if @user.id!=current_user.id %>
    <% if @user.followers.where(id: current_user.id).present? %>
      <td><%= link_to "Unfollow", unfollow_profile_path(@user.id), method: :delete %></td>
    <% else %>
      <td><%= link_to "Follow", follow_profile_path(@user.id), method: :post %></td>
    <% end %>
  <% end %>
</p>
<br>

<h1>Tweets</h1>
<%= render partial: '/home/tweets', locals: { tweets: @user.tweets } %>
<br>


<h1>Following</h1>
<% if @user.following.present? %>
  <table>
    <tbody>
      <% @user.following.each do |following| %>
        <tr>
          <td><%= following.email %></td>
          <% if @user.id==current_user.id %>
            <td><%= link_to "Unfollow", unfollow_profile_path(following.id), method: :delete %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  Not following any user yet.
<% end %>
<br><br>

<h1>Followers</h1>
<% if @user.followers.present? %>
  <table>
    <tbody>
      <% @user.followers.each do |following| %>
        <tr>
          <td><%= following.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  You have no followers.
<% end %>